#/* ======================================================================= */
#/*  QUALCOMM TECHNOLOGIES, INC.                                            */
#/*                                                                         */
#/*  HVX Intrinsics Examples with Boundary Conditions                       */
#/*                                                                         */
#/* ----------------------------------------------------------------------- */
#/*          Copyright (c) 2016 QUALCOMM TECHNOLOGIES Incorporated.         */
#/*                           All Rights Reserved.                          */
#/*                  QUALCOMM Confidential and Proprietary                  */
#/* ======================================================================= */

CURR_DIR = $(shell pwd)
INTRINSICS_TEST_TOP_DIR = ${CURR_DIR}/..
TESTNAME = $(shell basename ${CURR_DIR})

include ../Makefile.common

include ../Makefile.rules

export LD_LIBRARY_PATH=${HALIDE_ROOT}/lib
