/**=============================================================================
Copyright (c) 2017 QUALCOMM Technologies Incorporated.
All Rights Reserved Qualcomm Proprietary
=============================================================================**/
#ifndef QMATH_SAMPLE_IDL
#define QMATH_SAMPLE_IDL

#include "AEEStdDef.idl"

interface qmath_sample {

AEEResult quadratic(
	);
};

#endif //QMATH_SAMPLE_IDL
