#ifndef _GRAPHITE_MOD_FWK_H_
#define _GRAPHITE_MOD_FWK_H_
/*==============================================================================
  @file graphite_mod_fwk.h
  @brief this file contains Graphite framework module definitions

  Copyright (c) 2016 Qualcomm Technologies, Inc.(QTI)
  All rights reserved.
  Qualcomm Technologies Proprietary and Confidential.
==============================================================================*/

/*==============================================================================
                       EDIT HISTORY FOR FILE

  This section contains comments describing changes made to this file.
  Notice that changes are listed in reverse chronological order.

  $header:

  when       who        what, where, why
  --------   --- ------------------------------------------------------
  04/22/16  likhengp    Created file.
==============================================================================*/

/*------------------------------------------------------------------------------
 *  Header Includes
 *----------------------------------------------------------------------------*/
#include "mmdefs.h"

/*------------------------------------------------------------------------------
 *  Module ID Definitions
 *----------------------------------------------------------------------------*/
/*
  ID of the Graphite framework module, which is used to identify a generic
  framework module.

  The Instance ID for this module will always be 0.

  This module supports the parameter IDs that are listed below in this header
  file.

  @calibration_hdr_fields
  module_id -- GRAPHITE_MODULE_FWK
*/
#define GRAPHITE_MODULE_FWK 0x00020001

/*------------------------------------------------------------------------------
 *  Param ID Definitions
 *----------------------------------------------------------------------------*/
/*
  ID of the parameter used for #GRAPHITE_PARAM_ID_MODULE_LIST, which is used to
  send a list of module definitions.

  @calibration_hdr_fields
  param_id -- GRAPHITE_PARAM_ID_MODULE_LIST
*/
#define GRAPHITE_PARAM_ID_MODULE_LIST 0x00020002

/* Bitmask for graphite_module_t metadata field download into island/non-island
   heap flag.
*/
#define GRAPHITE_BIT_MASK_MOD_INSTANTIATE_HEAP_FLAG (0x0001)

/* Bit shift for graphite_module_t metadata field download into
   island/non-island heap flag.
*/
#define GRAPHITE_SHIFT_MOD_INSTANTIATE_HEAP_FLAG 0

/*
  Module definition uniquely defines a module, and has metadata on how this
  module instance should be downloaded and instantiated in memory.
 */
typedef struct graphite_module_t graphite_module_t;

#include "graphite_begin_pack.h"
struct graphite_module_t
{
  uint32_t module_id;
  /**<  Any non-zero value.
        A unique identifier for a particular module */

  uint16_t instance_id;
  /**<  Valid 16-bit value.
        A unique identifier for a particular instance of a module. The
        combination of module ID and instance ID needs to be unique across all
        modules in the WDSP.*/

  uint16_t metadata;
  /**<  Bits 15:1 - Reserved, must be set to 0.
        Bits 0    - 0: module needs to be instantiated in non-Island heap.
                    1: module needs to be instantiated in Island heap if
                       possible, but if Island heap is full, the module will be
                       instantiated in non-Island heap instead.

        Metadata gives more information on how this module needs to be
        instantiated.

        Note: this field is ignored for GRAPHITE_CMD_CLOSE.*/
  uint16_t max_input_pins;
  /**<  Valid 16-bit value.
        The maximum number of input streams that the module can accept.
        Note that the active number of incoming connections can be less
        than this value.

        Note: this field is ignored for GRAPHITE_CMD_CLOSE.*/

  uint16_t max_output_pins;
  /**<  Valid 16-bit value.
        The maximum number of output streams generated by the module.
        Note that the active number of outputs for the module can be less
        than this value

        Note: this field is ignored for GRAPHITE_CMD_CLOSE.*/
}
#include "graphite_end_pack.h"
;

/*
  ID of the parameter used for #GRAPHITE_PARAM_ID_CONNECT, which is used to
  send a list of connection/edge definitions.

  This param ID is used to identify the payload as connections that should be
  set up by Graphite between modules listed in the payload.

  GRAPHITE_PARAM_ID_CONNECT and GRAPHITE_PARAM_ID_DISCONNECT share
  the same payload format.

  @calibration_hdr_fields
  param_id -- GRAPHITE_PARAM_ID_CONNECT
*/
#define GRAPHITE_PARAM_ID_CONNECT 0x00020003

/*
  ID of the parameter used for #GRAPHITE_PARAM_ID_DISCONNECT, which is used to
  send a list of connection/edge definitions.

  This param ID is used to identify the payload as connections that
  should be torn down by Graphite between modules listed in the payload.

  GRAPHITE_PARAM_ID_CONNECT and GRAPHITE_PARAM_ID_DISCONNECT share
  the same payload format.

  @calibration_hdr_fields
  param_id -- GRAPHITE_PARAM_ID_DISCONNECT
*/
#define GRAPHITE_PARAM_ID_DISCONNECT 0x00020004

/*
  Part of payload for GRAPHITE_PARAM_ID_CONNECT/DISCONNECT calibrations that
  define graph connections.

  Module definition for a module that is the source of a connection/edge.
  num_destination_modules specifies how many destination modules are connected
  to this source module.

  Immediately following this will be the first graphite_edge_dest_module_t
  connected to this source module.
 */
typedef struct graphite_edge_src_module_t graphite_edge_src_module_t;

#include "graphite_begin_pack.h"
struct graphite_edge_src_module_t
{
  uint32_t module_id;
  /**<  Any non-zero value.
        A unique identifier for a particular module */

  uint16_t instance_id;
  /**<  Valid 16-bit value.
        A unique identifier for a particular instance of a module. The
        combination of module ID and
        instance ID needs to be unique across all modules in the WDSP.*/

  uint16_t num_destination_modules;
  /**<  Valid 32-bit number.
        Number of destination modules for connections/edges originating from
        this module. */
}
#include "graphite_end_pack.h"
;

/*
  Part of payload for GRAPHITE_PARAM_ID_CONNECT/DISCONNECT calibrations that
  define graph connections.

  Module definition for a module that is the destination of a connection/edge.
  num_edges specifies the number of connections/edges there are between this
  destination module and its source module.

  Immediately following this will be the first graphite_edge_t between this
  destination module and its source module.
*/
typedef struct graphite_edge_dest_module_t graphite_edge_dest_module_t;

#include "graphite_begin_pack.h"
struct graphite_edge_dest_module_t
{
  uint32_t module_id;
  /**<  Any non-zero value.
        A unique identifier for a particular module */

  uint16_t instance_id;
  /**<  Valid 16-bit value.
        A unique identifier for a particular instance of a module. The
        combination of module ID and
        instance ID needs to be unique across all modules in the WDSP.*/

  uint16_t num_edges;
  /**<  Valid 32-bit number.
        Number of connections/edges specified between the given source and
     destination modules. */
}
#include "graphite_end_pack.h"
;

/*
  Part of payload for GRAPHITE_PARAM_ID_CONNECT/DISCONNECT calibrations that
  define graph connections.

  Edge definition that defines the pin IDs for the source and destination
  modules that this edge connects.

  If there is more than one edge between the current source and destination
  modules, then the second edge will be immediately after this structure in the
  payload memory.

  If this is the last edge definition for the current source and destination
  modules, and there are more destination modules that the current source
  module is connected to, then immediately following this will be the next
  destination module.

  If this is the last edge definition for the last destination module connected
  to the current source module, and the payload has not been fully consumed,
  then immediately following this will be the next source module definition.
*/
typedef struct graphite_edge_t graphite_edge_t;

#include "graphite_begin_pack.h"
struct graphite_edge_t
{
  uint16_t source_pin_id;
  /**<  Valid 16-bit value.
        Pin ID specifying the origin of this edge. */

  uint16_t destination_pin_id;
  /**<  Valid 16-bit value.
        Pin ID specifying the termination of this edge. */
}
#include "graphite_end_pack.h"
;

/*
  ID of the parameter used for #GRAPHITE_PARAM_ID_INDIRECT_CALIB_DATA, which
  is used to identify the calibration payload which was previously sent by
  GRAPHITE_CMD_LOAD_DATA command.

  @calibration_hdr_fields
  param_id -- GRAPHITE_PARAM_ID_INDIRECT_CALIB_DATA
*/
#define GRAPHITE_PARAM_ID_INDIRECT_CALIB_DATA 0x00020005

/*
  Payload for #GRAPHITE_PARAM_ID_INDIRECT_CALIB_DATA.

  Contains the address on Graphite Server where the data was loaded using
  GRAPHITE_CMD_LOAD_DATA was returned to client as GRAPHITE_CMDRSP_LOAD_DATA.
*/
typedef struct graphite_indirect_calib_data_t graphite_indirect_calib_data_t;

#include "graphite_begin_pack.h"
struct graphite_indirect_calib_data_t
{
  uint32_t addr;
  /**<  Valid 32-bit value.
        This is the address of a calibration payload previously sent by a
        client to the Graphite server through the GRAPHITE_CMD_LOAD_DATA
        command. */

  uint32_t size;
  /**<  Valid 32-bit value.
        This is the size of the payload pointed to by the addr field */
}
#include "graphite_end_pack.h"
;

/*
  ID of the parameter used for #GRAPHITE_PARAM_ID_EVENT_REGISTER, which
  is used to register for Graphite events.

  Graphite client can register/de-register for events with a module in graph.
  This is enabled by a module framework calibration data defined in
  #graphite_register_event_t.
  After a client registers for a particular MID, IID and Event ID – all events
  matching this signature will be forward to the client.

  Use the following calibration configuration to register for generic
  Graphite events.
    module_id = GRAPHITE_MODULE_FWK
    instance_id = 0
    param_id = GRAPHITE_PARAM_ID_EVENT_REGISTER

  @calibration_hdr_fields
  param_id -- GRAPHITE_PARAM_ID_EVENT_REGISTER
*/
#define GRAPHITE_PARAM_ID_EVENT_REGISTER 0x00020006

/*
  ID of the parameter used for #GRAPHITE_PARAM_ID_EVENT_DEREGISTER, which
  is used to register for Graphite events.

  Use the following calibration configuration to deregister for generic
  Graphite events.
    module_id = GRAPHITE_MODULE_FWK
    instance_id = 0
    param_id = GRAPHITE_PARAM_ID_EVENT_DEREGISTER

  This parameter uses the same payload #graphite_register_event_t as
  #GRAPHITE_PARAM_ID_EVENT_REGISTER.

  @calibration_hdr_fields
  param_id -- GRAPHITE_PARAM_ID_EVENT_DEREGISTER
*/
#define GRAPHITE_PARAM_ID_EVENT_DEREGISTER 0x00020007

/*
  Payload for
  #GRAPHITE_PARAM_ID_EVENT_REGISTER/GRAPHITE_PARAM_ID_EVENT_DEREGISTER.
*/
typedef struct graphite_register_event_t graphite_register_event_t;

#include "graphite_begin_pack.h"
struct graphite_register_event_t
{
  uint32_t module_id;
  /**<  Any non-zero value.
        A unique identifier for a particular module to get events from. */

  uint16_t instance_id;
  /**<  Valid 16-bit value.
        A unique identifier for a particular instance of a module to get
        events from. The combination of module ID and instance ID needs to
        be unique across all modules in the WDSP.
        instance_id is not applicable to framework modules, and will be
        ignored.*/

  uint16_t reserved;
  /**<  Reserved field, must be set to 0. */

  uint32_t param_id;
  /**<  Valid event param ID.
        Register: Indicates a the ID for the event the client wants to
                  receive.
        Deregister: Indicates the ID for the event the Client wants to
                    stop receiving events from. */
}
#include "graphite_end_pack.h"
;

#endif /* _GRAPHITE_MOD_FWK_H_ */
