/**=============================================================================
Copyright (c) 2017 QUALCOMM Technologies Incorporated.
_all Rights Reserved Qualcomm Proprietary
=============================================================================**/
#ifndef QFXP_SAMPLE_IDL
#define QFXP_SAMPLE_IDL

#include "AEEStdDef.idl"
#include "remote.idl"

interface qfxp_sample : remote_handle64{

AEEResult run(
	);
};


#endif //QFXP_SAMPLE_IDL
