cd /prj/dsp/austin/llvm/test/users/anurkuma/all_releases/hexagon/8.3.07/installed; if [ ! -d /prj/dsp/austin/llvm/test/users/anurkuma/all_releases/hexagon/8.3.07/installed ]; then exit 1; fi;
rm -f ./Tools/bin/llvm-ranlib
rm -f ./Tools/bin/llvm-lib
rm -f ./Tools/bin/hexagon-ar
rm -f ./Tools/bin/hexagon-ranlib
rm -f ./Tools/bin/hexagon-clang
rm -f ./Tools/bin/clang
rm -f ./Tools/bin/hexagon-clang++
rm -f ./Tools/bin/hexagon-clang-cl
rm -f ./Tools/bin/hexagon-clang-cpp
rm -f ./Tools/bin/hexagon-c++filt
rm -f ./Tools/bin/hexagon-nm
rm -f ./Tools/bin/hexagon-size
rm -f ./Tools/bin/hexagon-readelf
rm -f ./Tools/bin/hexagon-link
rm -f ./Tools/lib/libclang.so
rm -f ./Tools/lib/python2.7/site-packages/lldb/_lldb.so
rm -f ./Tools/lib/liblldb.so.7
rm -f ./Tools/lib/liblldb.so
rm -f ./Tools/lib/liblldbIntelFeatures.so
rm -f ./Tools/lib/libLW.so
rm -f ./Tools/lib/libSortPGO.so
rm -f ./Tools/lib/libSectionBudgetingV2.so
rm -f ./Tools/lib/libc++abi.so.1
rm -f ./Tools/lib/libc++.so.1
rm -f ./Tools/lib/libc++abi.so
rm -f ./Tools/lib/libedit.so
rm -f ./Tools/lib/libedit.so.0
rm -f ./Tools/lib/libpython2.7.so
rm -f ./Tools/lib/pkgconfig/python.pc
rm -f ./Tools/lib/pkgconfig/python2.pc
rm -f ./Tools/libexec/python
rm -f ./Tools/libexec/python2
rm -f ./Tools/target/hexagon/lib/v67/G0/pic/libc++abi.so.1
rm -f ./Tools/target/hexagon/lib/v67/G0/pic/libc++abi.so
rm -f ./Tools/target/hexagon/lib/v67/G0/pic/libc++.so.1
rm -f ./Tools/target/hexagon/lib/v67/G0/pic/libc++.so
rm -f ./Tools/target/hexagon/lib/v61/G0/pic/libc++abi.so.1
rm -f ./Tools/target/hexagon/lib/v61/G0/pic/libc++abi.so
rm -f ./Tools/target/hexagon/lib/v61/G0/pic/libc++.so.1
rm -f ./Tools/target/hexagon/lib/v61/G0/pic/libc++.so
rm -f ./Tools/target/hexagon/lib/v55/G0/pic/libc++abi.so.1
rm -f ./Tools/target/hexagon/lib/v55/G0/pic/libc++abi.so
rm -f ./Tools/target/hexagon/lib/v55/G0/pic/libc++.so.1
rm -f ./Tools/target/hexagon/lib/v55/G0/pic/libc++.so
rm -f ./Tools/target/hexagon/lib/v62/G0/pic/libc++abi.so.1
rm -f ./Tools/target/hexagon/lib/v62/G0/pic/libc++abi.so
rm -f ./Tools/target/hexagon/lib/v62/G0/pic/libc++.so.1
rm -f ./Tools/target/hexagon/lib/v62/G0/pic/libc++.so
rm -f ./Tools/target/hexagon/lib/v60/G0/pic/libc++abi.so.1
rm -f ./Tools/target/hexagon/lib/v60/G0/pic/libc++abi.so
rm -f ./Tools/target/hexagon/lib/v60/G0/pic/libc++.so.1
rm -f ./Tools/target/hexagon/lib/v60/G0/pic/libc++.so
rm -f ./Tools/target/hexagon/lib/v65/G0/pic/libc++abi.so.1
rm -f ./Tools/target/hexagon/lib/v65/G0/pic/libc++abi.so
rm -f ./Tools/target/hexagon/lib/v65/G0/pic/libc++.so.1
rm -f ./Tools/target/hexagon/lib/v65/G0/pic/libc++.so
rm -f ./Tools/target/hexagon/lib/v67t/G0/pic/libc++abi.so.1
rm -f ./Tools/target/hexagon/lib/v67t/G0/pic/libc++abi.so
rm -f ./Tools/target/hexagon/lib/v67t/G0/pic/libc++.so.1
rm -f ./Tools/target/hexagon/lib/v67t/G0/pic/libc++.so
rm -f ./Tools/target/hexagon/lib/v66/G0/pic/libc++abi.so.1
rm -f ./Tools/target/hexagon/lib/v66/G0/pic/libc++abi.so
rm -f ./Tools/target/hexagon/lib/v66/G0/pic/libc++.so.1
rm -f ./Tools/target/hexagon/lib/v66/G0/pic/libc++.so
rm -f /prj/dsp/austin/llvm/test/users/anurkuma/all_releases/hexagon/8.3.07/installed/Uninstall_Qualcomm_Hexagon_LLVM_Tools/linux_unlink.sh
