/**=============================================================================
Copyright (c) 2017 QUALCOMM Technologies Incorporated.
_all Rights Reserved Qualcomm Proprietary
=============================================================================**/
#ifndef qprintf_EXAMPLE_IDL
#define qprintf_EXAMPLE_IDL

#include "AEEStdDef.idl"
#include "remote.idl"

interface qprintf_example : remote_handle64{

AEEResult run(
	);
};


#endif //qprintf_EXAMPLE_IDL
